### PR TITLE
Resolve the “Command failed: git write-tree” error

### LINKED ISSUE #25: sporadic git command failed "git write-tree"
For a while I'd thought this was because I was doing simultaneous deployments, but recently it has happened when only running a single deployment.

```
$ sls deploy

  Error --------------------------------------------------

  Command failed: git write-tree
fatal: Unable to create '/Users/peter/workspace/my-serverless-app/.git/index.lock': File exists.
```

A second run without any intervention on my part (I did not look for or delete an index.lock file) succeeded, which suggests to me that there is actually some kind of race condition inside this plugin?

### PR DESCRIPTION
**Pull request by iamakulov**
Closes #25.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -96,19 +96,19 @@ export default class ServerlessGitVariables {
     }
 
     for (const functionName of this.serverless.service.getAllFunctions()) {
-      const func = this.serverless.service.getFunction(functionName);
```
Comment (atz) [inline src/index.js]: I think you still want this semicolon.  At least, if the other `const` declarations need one, this would need one, too.

**Comment by atz** [comment]
Since CI/eslint is complaining:
```
/home/travis/build/jacob-meacham/serverless-plugin-git-variables/src/index.js
  101:48  error  Extra semicolon  semi
  104:52  error  Extra semicolon  semi
  107:52  error  Extra semicolon  semi
  110:54  error  Extra semicolon  semi
```
Seems like it doesn't want *any* of those semicolons.  That would be consistent w/ the rest of the file, e.g. [line 70](https://github.com/jacob-meacham/serverless-plugin-git-variables/pull/27/files#diff-1fdf421c05c1140f6d71444ea2b27638L70).

**Comment by iamakulov** [comment]
Fixed those semicolons, thanks! Missed them somehow

File: src/index.js [hunk 2]
```diff
@@ -89,29 +89,27 @@ export default class ServerlessGitVariables {
...
+      this.exportGitVariable(func, 'GIT_COMMIT_SHORT', sha1)
+
+      const commit = await this._getValue('commit')
+      this.exportGitVariable(func, 'GIT_COMMIT_LONG', commit)
+
+      const branch = await this._getValue('branch')
+      this.exportGitVariable(func, 'GIT_BRANCH', branch)
+
+      const isDirty = await this._getValue('isDirty')
+      this.exportGitVariable(func, 'GIT_IS_DIRTY', isDirty)
```
Comment (jacob-meacham) [inline src/index.js]: Looks like this is missing GIT_REPOSITORY in addition to these others

File: src/index.js [hunk 3]
```diff
@@ -89,29 +89,27 @@ export default class ServerlessGitVariables {
...
-        this.exportGitVariable(func, 'GIT_BRANCH', branch)
-        this.exportGitVariable(func, 'GIT_IS_DIRTY', isDirty)
-        this.exportGitVariable(func, 'GIT_REPOSITORY', repository)
-      })
-    })
-    return Promise.all(promises)
+    for (const functionName of this.serverless.service.getAllFunctions()) {
+      const func = this.serverless.service.getFunction(functionName)
+
+      const sha1 = await this._getValue('sha1')
```
Comment (jacob-meacham) [inline src/index.js]: Now that this reads more fluently, can you move these `await`s outside of the for loop? Because we cache the values, in practice it won't be any slower, but it may look a little surprising to future readers - without looking at the implementation of _getValue, it reads as though we're calling into git many more times than required

**Comment by atz** [comment]
Cool, got CI passing, thx.

**Comment by petergaultney** [comment]
Would love to see this make it in. Slower is better than the current situation, where I nearly always have to run my serverless deployment twice to make it succeed.

File: src/index.js (hunk 2 above)
Comment (iamakulov) [reply src/index.js]: Done!

File: src/index.js (hunk 3 above)
Comment (iamakulov) [reply src/index.js]: Good point, done!

**Comment by iamakulov** [comment]
> One concern I have is that because this is now serial on git, this will cause all serverless commands to run more slowly. Can you do a quick before/after on latency for this?

Sure.

* I wrapped the insides of `exportGitVariables` with `console.time()`/`timeEnd()` (adding `.then()` to `Promise.all()` in case of code from `master`).
* I also removed the `GIT_IS_DIRTY` export because it was triggering the git error from #25 on my machine
* I did 5 measurements by running and then cancelling `serverless deploy` on one of my projects

<details>
<summary>Code versions I used</summary>

Code from `master` with `console.time()`:

```js
exportGitVariables() {
    const exportGitVariables =
        this.serverless.service.custom &&
        this.serverless.service.custom.exportGitVariables;
    if (exportGitVariables === false) {
        return Promise.resolve();
    }

    console.time('promises');
    const promises = this.serverless.service
        .getAllFunctions()
        .map(functionName => {
            return Promise.all([
                this._getValue('sha1'),
                this._getValue('commit'),
                this._getValue('branch'),
                // this._getValue('isDirty'),
                this._getValue('repository'),
            ]).then(([sha1, commit, branch, repository]) => {
                const func = this.serverless.service.getFunction(
                    functionName,
                );
                this.exportGitVariable(func, 'GIT_COMMIT_SHORT', sha1);
                this.exportGitVariable(func, 'GIT_COMMIT_LONG', commit);
                this.exportGitVariable(func, 'GIT_BRANCH', branch);
                // this.exportGitVariable(func, 'GIT_IS_DIRTY', isDirty);
                this.exportGitVariable(func, 'GIT_REPOSITORY', repository);
            });
        });
    return Promise.all(promises).then(i => {
        console.timeEnd('promises');
        return i;
    });
}
```

Code from this PR with `console.time()`:

```js
async exportGitVariables() {
    const exportGitVariables =
        this.serverless.service.custom &&
        this.serverless.service.custom.exportGitVariables;
    if (exportGitVariables === false) {
        return;
    }

    console.time('async');

    const sha1 = await this._getValue('sha1');
    const commit = await this._getValue('commit');
    const branch = await this._getValue('branch');
    const repository = await this._getValue('repository');

    for (const functionName of this.serverless.service.getAllFunctions()) {
        const func = this.serverless.service.getFunction(functionName);

        this.exportGitVariable(func, 'GIT_COMMIT_SHORT', sha1);
        this.exportGitVariable(func, 'GIT_COMMIT_LONG', commit);
        this.exportGitVariable(func, 'GIT_BRANCH', branch);
        this.exportGitVariable(func, 'GIT_REPOSITORY', repository);
    }

    console.timeEnd('async');
}
```
</details>
 
And, on my machine, it looks like the new version is actually faster:

<image src="https://user-images.githubusercontent.com/2953267/60249073-a75ab200-98cc-11e9-9d7d-acbdb625d3f0.png" width="300">

**Comment by jacob-meacham** [comment]
Thanks @iamakulov !

**Comment by jacob-meacham** [comment]
Released as 3.3.2
